spring:

  application:
    name: mts-homework-final-application-service

  datasource:
    url: jdbc:postgresql://localhost:5432/final_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        format_sql: false
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
    show-sql: false
    defer-datasource-initialization: true
  main:
    allow-bean-definition-overriding: true

  cloud:
    function:
      definition: consumeStockMessage
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: false
      bindings:
        consumeStockMessage-in-0:
          destination: final.stock
          contentType: application/json
          group: ${spring.application.name}-group
          useNativeDecoding: true
          consumer:
            autoCommitOffset: false
            startOffset: latest
            ackMode: MANUAL
            backOffInitialInterval: 10000
            maxAttempts: 5
            enableDlq: false

server:
  port: 7456
  error:
    include-message: always